### ISSUE TITLE
Just curious if a part 4 is still in the works

### ISSUE THREAD

**Issue by matthewhively** [Brett208/OP2MissionRescueEscort#1]
Got through the 3rd mission tonight and was disappointed that it just ended there.

**Comment by Brett208** [comment]
@matthewhively, 

Glad to hear you enjoyed the missions. Part four is partially complete (Mesa Missions), but I never got around to finishing it. I would like to pick it back up, but it is on the back-burner for now as I am working on a full length game unrelated to Outpost 2. The repository is at ([OP2MissionMesaMissions](https://github.com/Brett208/OP2MissionMesaMissions)) if you want to follow it to see when more progress is made.

**Comment by matthewhively** [comment]
I will do that. Thanks.
